"""New Migration

Revision ID: 4e81d366544b
Revises: 72dbfbb6a099
Create Date: 2022-03-16 09:14:44.605018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e81d366544b'
down_revision = '72dbfbb6a099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('description', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'description')
    # ### end Alembic commands ###
