"""Initial Migration

Revision ID: 72dbfbb6a099
Revises: 
Create Date: 2022-03-14 08:08:34.189126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dbfbb6a099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_writers_email', table_name='writers')
    op.drop_index('ix_writers_username', table_name='writers')
    op.drop_table('writers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='writers_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='writers_pkey')
    )
    op.create_index('ix_writers_username', 'writers', ['username'], unique=False)
    op.create_index('ix_writers_email', 'writers', ['email'], unique=False)
    # ### end Alembic commands ###
